%
maindir = '/Users/psyc1586_admin/GVB_data/harmonisation_work/00_aa_skullImprovement_Oct2025/run_harmonisation_pipelines';
outdir  = 'LR_LME_approaches';

% Load data
data = load(fullfile(maindir,'data_ori.mat'));
data = data.final_ori;
% IDP list
idp_list = {'T1_SIENAX_periphGM_norm_vol',...
'T1_SIENAX_CSF_norm_vol',...
'T1_SIENAX_GM_norm_vol',...
'T1_SIENAX_WM_norm_vol',...
'T1_SIENAX_brain_norm_vol',...
'T1_FIRST_left_hippocampus',...
'T1_FIRST_right_hippocampus'}';

age_col     = 'Final_Age';
time_col    = 'timepoint';
subj_col    = 'subjectID';
site_col    = 'Site';
scanner_col = 'Scanner';

data = data(~ismember(data.(subj_col), 'UCL006'),:);


% Example 1: Site as fixed effect with LME
harmonised_LME_site = harmonise_LR_LME(data, 'site', 'LME', idp_list, ...
                        'age_var', age_col, 'timepoint_var', time_col, ...
                        'subject_var', subj_col, 'site_var', site_col, 'scanner_var', scanner_col,...
                        'zscore_age', true);
harmonised_LME_site.Properties.VariableNames(ismember(harmonised_LME_site.Properties.VariableNames, idp_list)) = ...
    strcat('harmonisedLME_', idp_list);
writetable(harmonised_LME_site, fullfile(maindir, outdir, 'harmonised_LME_site.csv'))

% Example 2: Scanner as fixed effect with LME
harmonised_LME_scanner = harmonise_LR_LME(data, 'scanner', 'LME', idp_list, ...
                        'age_var', age_col, 'timepoint_var', time_col, ...
                        'subject_var', subj_col, 'site_var', site_col, 'scanner_var', scanner_col,...
                        'zscore_age', true);
harmonised_LME_scanner.Properties.VariableNames(ismember(harmonised_LME_scanner.Properties.VariableNames, idp_list)) = ...
    strcat('harmonisedLME_', idp_list);
writetable(harmonised_LME_scanner, fullfile(maindir, outdir, 'harmonised_LME_scanner.csv'))


% Example 3: Scanner fixed + site random with LME (your use case)
harmonised_LME_scannersite = harmonise_LR_LME(data, {'scanner','site'}, 'LME', idp_list, ...
                        'age_var', age_col, 'timepoint_var', time_col, ...
                        'subject_var', subj_col, 'site_var', site_col, 'scanner_var', scanner_col,...
                        'zscore_age', true);
harmonised_LME_scannersite.Properties.VariableNames(ismember(harmonised_LME_scannersite.Properties.VariableNames, idp_list)) = ...
    strcat('harmonisedLME_', idp_list);
writetable(harmonised_LME_scannersite, fullfile(maindir, outdir, 'harmonised_LME_scannersite.csv'))


% Example 4: Scanner as fixed effect with LR
harmonised_LR_scanner = harmonise_LR_LME(data, 'scanner', 'LR', idp_list, ...
                        'age_var', age_col, 'timepoint_var', time_col, ...
                        'subject_var', subj_col, 'site_var', site_col, 'scanner_var', scanner_col,...
                        'zscore_age', true);
harmonised_LR_scanner.Properties.VariableNames(ismember(harmonised_LR_scanner.Properties.VariableNames, idp_list)) = ...
    strcat('harmonisedLR_', idp_list);
writetable(harmonised_LR_scanner, fullfile(maindir, outdir, 'harmonised_LR_scanner.csv'))




% Example 5: Site as fixed effect with LR
harmonised_LR_site = harmonise_LR_LME(data, 'site', 'LR', idp_list, ...
                        'age_var', age_col, 'timepoint_var', time_col, ...
                        'subject_var', subj_col, 'site_var', site_col, 'scanner_var', scanner_col,...
                        'zscore_age', true);
harmonised_LR_site.Properties.VariableNames(ismember(harmonised_LR_site.Properties.VariableNames, idp_list)) = ...
    strcat('harmonisedLR_', idp_list);
writetable(harmonised_LR_site, fullfile(maindir, outdir, 'harmonised_LR_site.csv'))

